# Site settings
title: 八宝莉的技术博客
email: coolnameismy@hotmail.com
description: > #八宝莉的技术博客
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://curry-wei98.github.io/" # the base hostname & protocol for your site
# url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
twitter_username: superwei
github_username: https://curry-wei98.github.io/

# Build settings
#markdown: kramdown
permalink: /:year/:month/:day/:title.html   #博文的固定链接
paginate: 10                                #分页时每页博文数量
author:                                     #自定义常亮
  name: 八宝莉
  email: fw98989898@gmail.com
  link: https://curry-wei98.github.io/
  weibo: https://weibo.com/u/2404903781
  github: https://curry-wei98.github.io/
title: 八宝莉的技术博客                             #自定义常量

# avatar头像及Favicon
avatar: https://github.com/Curry-wei98/asd/blob/master/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20200412005824.jpg
#favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

locals:                                     #自定义常量
  tags: 标签
  about: 关于
active: 技术                                 #自定义常量
subscribe_rss: /pages/atom.xml              #订阅地址
markdown: kramdown                         #markdown解释器

# google analytics 设置
#ga:
#  id:
#  url:
#

# baidu analytics 设置

# disqus 设置
disqus:
  shortname: coolnameismy

theme: jekyll-theme-cayman